-- Money Compass initial schema.
--
-- Deviation from the spec worth knowing about: enums are VARCHAR columns with
-- CHECK constraints rather than native Postgres ENUM types. Native enums are
-- awkward to map through Hibernate (they need a custom type) and every value
-- addition needs an ALTER TYPE that cannot run inside a transaction. The
-- constraint gives the same integrity guarantee at the database level.

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id            UUID         PRIMARY KEY,
    email         VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    profile_type  VARCHAR(16)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT users_profile_type_chk
        CHECK (profile_type IN ('STUDENT', 'PROFESSIONAL', 'RETIREE'))
);

-- ---------------------------------------------------------------------------
-- questions
--
-- `code` is the stable business key. Everything else in the system references
-- a question by code, never by id, so seed data can be reordered freely.
-- ---------------------------------------------------------------------------
CREATE TABLE questions (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(64) NOT NULL UNIQUE,
    text                TEXT        NOT NULL,
    type                VARCHAR(16) NOT NULL,
    options             JSONB,
    category            VARCHAR(24) NOT NULL,
    applicable_profiles TEXT[]      NOT NULL,
    weight              INT         NOT NULL DEFAULT 1,
    rubric              JSONB,
    CONSTRAINT questions_type_chk
        CHECK (type IN ('SINGLE', 'MULTI', 'NUMBER', 'SCALE')),
    CONSTRAINT questions_category_chk
        CHECK (category IN ('BUDGETING', 'SAVING', 'DEBT', 'INVESTING',
                            'COMPOUNDING', 'RISK', 'RETIREMENT')),
    CONSTRAINT questions_weight_chk
        CHECK (weight >= 1)
);

CREATE INDEX idx_questions_category ON questions (category);

-- ---------------------------------------------------------------------------
-- question_rules
--
-- Branching. When `question_code` has been answered and `condition` matches
-- that answer, `next_question_code` becomes eligible. Lower priority first.
-- ---------------------------------------------------------------------------
CREATE TABLE question_rules (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_code      VARCHAR(64) NOT NULL REFERENCES questions (code) ON DELETE CASCADE,
    condition          JSONB       NOT NULL,
    next_question_code VARCHAR(64) NOT NULL REFERENCES questions (code) ON DELETE CASCADE,
    priority           INT         NOT NULL DEFAULT 100
);

CREATE INDEX idx_question_rules_question_code ON question_rules (question_code);

-- ---------------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
    id           UUID        PRIMARY KEY,
    user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(16) NOT NULL,
    started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT sessions_status_chk
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED'))
);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);

-- ---------------------------------------------------------------------------
-- answers
--
-- One row per answered question per session. The unique constraint is what
-- makes the questionnaire engine's "exclude already answered" logic safe under
-- a double-submit.
-- ---------------------------------------------------------------------------
CREATE TABLE answers (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    UUID        NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    question_code VARCHAR(64) NOT NULL REFERENCES questions (code),
    value         JSONB       NOT NULL,
    answered_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT answers_session_question_uk UNIQUE (session_id, question_code)
);

CREATE INDEX idx_answers_session_id ON answers (session_id);

-- ---------------------------------------------------------------------------
-- literacy_scores
--
-- `total` and `category_breakdown` are computed deterministically in Java.
-- `narrative_json` is the only LLM-authored column. `provider_used` and
-- `model_used` record which provider actually served the request, which is
-- what makes the Bedrock fallback demonstrable rather than merely claimed.
-- ---------------------------------------------------------------------------
CREATE TABLE literacy_scores (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         UUID        NOT NULL UNIQUE REFERENCES sessions (id) ON DELETE CASCADE,
    total              INT         NOT NULL,
    category_breakdown JSONB       NOT NULL,
    narrative_json     JSONB,
    provider_used      VARCHAR(32),
    model_used         VARCHAR(128),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT literacy_scores_total_chk CHECK (total BETWEEN 0 AND 100)
);

-- ---------------------------------------------------------------------------
-- risk_profiles
-- ---------------------------------------------------------------------------
CREATE TABLE risk_profiles (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      UUID        NOT NULL UNIQUE REFERENCES sessions (id) ON DELETE CASCADE,
    tolerance_score INT         NOT NULL,
    capacity_score  INT         NOT NULL,
    risk_band       VARCHAR(16) NOT NULL,
    allocation      JSONB       NOT NULL,
    narrative_json  JSONB,
    provider_used   VARCHAR(32),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT risk_profiles_tolerance_chk CHECK (tolerance_score BETWEEN 0 AND 100),
    CONSTRAINT risk_profiles_capacity_chk  CHECK (capacity_score  BETWEEN 0 AND 100),
    CONSTRAINT risk_profiles_band_chk
        CHECK (risk_band IN ('CONSERVATIVE', 'MODERATE', 'BALANCED',
                             'GROWTH', 'AGGRESSIVE'))
);
