-- Money Compass question bank v2, generated from prototype/index.html so the
-- real app asks exactly what the prototype does. Adds everything the
-- prototype's adaptive flow needs:
--
--   hint / unit / min_value / max_value / scale_labels  presentation
--   variants          per-profile overrides of text, hint, unit and options,
--                     e.g. {"STUDENT": {"text": "...", "options": {...}}}
--   clarifies         this question is a simpler re-ask of <clarifies>, only
--                     served when that one was answered "I don't know"
--   value_map         how a clarifier's option maps back onto the original
--                     question's answer, e.g. {"B": {"number": 2}}
--   ask_if            a follow-up's trigger, evaluated by AskIfCondition:
--                     {"selectedIn": {"question": q, "values": [...]}}
--                     {"unknownOrNumberBelow": {"question": q, "value": n}}
--                     {"unknownOrScaleAtMost": {"question": q, "value": n}}
--                     {"knowledgeGap": "<CATEGORY>"}
--   follow_up_reason  shown above a follow-up, saying why it was asked
--   advanced          skipped once the user says "I don't know" in that
--                     category without getting any of its knowledge right
--   sort_order        the order questions are served in
--   knowledge_topic   what to call the topic when the user misses it
--   wiki_title        a Wikipedia article to read up on it
--   active            false for questions from v1 that are no longer asked;
--                     kept (not deleted) because old answers reference them
--
-- Branching now lives in ask_if/clarifies, so question_rules is emptied.
-- A NULL rubric means "not scored" (age, income, dependents, clarifiers).

ALTER TABLE questions
    ADD COLUMN hint             TEXT,
    ADD COLUMN unit             VARCHAR(64),
    ADD COLUMN min_value        NUMERIC,
    ADD COLUMN max_value        NUMERIC,
    ADD COLUMN scale_labels     JSONB,
    ADD COLUMN variants         JSONB,
    ADD COLUMN clarifies        VARCHAR(64),
    ADD COLUMN value_map        JSONB,
    ADD COLUMN ask_if           JSONB,
    ADD COLUMN follow_up_reason TEXT,
    ADD COLUMN advanced         BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN sort_order       INT     NOT NULL DEFAULT 1000,
    ADD COLUMN knowledge_topic  TEXT,
    ADD COLUMN wiki_title       TEXT,
    ADD COLUMN active           BOOLEAN NOT NULL DEFAULT TRUE;

DELETE FROM question_rules;
UPDATE questions SET active = FALSE;

INSERT INTO questions (code, text, type, options, category, applicable_profiles, weight, rubric,
                       hint, unit, min_value, max_value, scale_labels, variants,
                       clarifies, value_map, ask_if, follow_up_reason,
                       advanced, sort_order, knowledge_topic, wiki_title) VALUES
('age', 'How old are you?', 'NUMBER', NULL, 'BUDGETING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, NULL, 'Not scored — it sets your retirement timeline and how much risk suits your stage of life.', 'years', 15, 100, NULL, '{"STUDENT":{"hint":"Not scored — it tells us how many years your money has to grow."},"RETIREE":{"hint":"Not scored — it shapes how long your savings need to last and how much risk suits you."}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 10, NULL, NULL),
('monthly_income', 'Roughly what is your monthly take-home income?', 'NUMBER', NULL, 'BUDGETING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, NULL, 'What reaches your account after tax and EPF: salary, pension plus regular withdrawals, or allowance and part-time pay. Not scored — it sizes your plan.', '₹ per month', NULL, NULL, NULL, '{"STUDENT":{"text":"How much money comes to you in a typical month?","unit":"₹ per month","hint":"Pocket money, allowance, stipend, scholarship, part-time or internship pay — whatever reaches you. Enter 0 if nothing comes regularly. Not scored — it sizes your plan."},"RETIREE":{"text":"Roughly how much comes in each month?","unit":"₹ per month","hint":"Pension, annuity, interest, rent and any regular withdrawals from your savings, after tax. Not scored — it sizes your plan."},"PROFESSIONAL":{"hint":"Your salary as it lands in your account — after tax, EPF and other deductions — plus any regular side or freelance income. Not scored — it sizes your plan."}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 20, NULL, NULL),
('monthly_income_range_student', 'No problem — roughly how much comes to you in a typical month?', 'SINGLE', '{"A":"Nothing regular","B":"Under ₹2,000","C":"₹2,000 – ₹5,000","D":"₹5,000 – ₹15,000","E":"More than ₹15,000"}'::jsonb, 'BUDGETING', ARRAY['STUDENT'], 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'monthly_income', '{"A":{"number":0},"B":{"number":1000},"C":{"number":3500},"D":{"number":10000},"E":{"number":20000}}'::jsonb, NULL, NULL, FALSE, 30, NULL, NULL),
('monthly_income_range', 'No problem — which range is your monthly take-home (salary, pension, or allowance) closest to?', 'SINGLE', '{"A":"Under ₹25,000","B":"₹25,000 – ₹50,000","C":"₹50,000 – ₹1,00,000","D":"₹1,00,000 – ₹2,00,000","E":"Above ₹2,00,000"}'::jsonb, 'BUDGETING', ARRAY['PROFESSIONAL','RETIREE'], 1, NULL, NULL, NULL, NULL, NULL, NULL, '{"RETIREE":{"text":"No problem — which range is your monthly income (pension, interest, rent and withdrawals together) closest to?"},"PROFESSIONAL":{"text":"No problem — which range is your monthly in-hand salary (plus any regular side income) closest to?"}}'::jsonb, 'monthly_income', '{"A":{"number":15000},"B":{"number":37500},"C":{"number":75000},"D":{"number":150000},"E":{"number":250000}}'::jsonb, NULL, NULL, FALSE, 40, NULL, NULL),
('budgeting_expense_tracking', 'How do you currently track your monthly expenses?', 'SINGLE', '{"A":"I don''t track them at all","B":"Rough mental estimate","C":"Spreadsheet or app, checked occasionally","D":"Detailed tracking, reviewed every month"}'::jsonb, 'BUDGETING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"optionPoints":{"A":0,"B":3,"C":7,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 50, NULL, 'Personal budget'),
('budgeting_needs_wants', 'Which of these is a “want” rather than a “need”?', 'SINGLE', '{"A":"Rent for a room near your college or work","B":"Groceries for cooking at home","C":"Upgrading to a new phone while yours still works fine","D":"A health insurance premium"}'::jsonb, 'BUDGETING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"correct":"C","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, '{"RETIREE":{"options":{"A":"Your regular medicines","B":"Groceries for cooking at home","C":"Upgrading to a new phone while yours still works fine","D":"A health insurance premium"}}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 60, 'needs vs. wants', 'Need'),
('budgeting_savings_rate', 'Roughly what percentage of your take-home income do you save or invest in a typical month?', 'NUMBER', NULL, 'BUDGETING', ARRAY['STUDENT','PROFESSIONAL'], 1, '{"numberThresholds":[{"min":20,"points":10},{"min":10,"points":6},{"min":0,"points":2}]}'::jsonb, 'Count SIPs, RDs, and money you move to savings. Leave out EPF — it''s already taken out before your take-home.', '% of take-home', NULL, NULL, NULL, '{"STUDENT":{"text":"Roughly what share of the money you get each month do you save or invest?","unit":"% of what you get","hint":"Count anything you put aside — money left in your savings account counts, and so does an SIP."}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 70, NULL, 'Saving'),
('budgeting_savings_rate_simple', 'Let''s try it another way — at the end of a typical month, how much of your income is usually left over?', 'SINGLE', '{"A":"Nothing, or I overspend","B":"A little — under a tenth of it","C":"Somewhere between a tenth and a fifth","D":"More than a fifth"}'::jsonb, 'BUDGETING', ARRAY['STUDENT','PROFESSIONAL'], 1, NULL, NULL, NULL, NULL, NULL, NULL, '{"STUDENT":{"text":"Let''s try it another way — at the end of a typical month, how much of your money is usually left over?"}}'::jsonb, 'budgeting_savings_rate', '{"A":{"number":0},"B":{"number":5},"C":{"number":15},"D":{"number":25}}'::jsonb, NULL, NULL, FALSE, 80, NULL, 'Saving'),
('budgeting_fixed_expenses', 'Which of these are usually fixed, hard-to-change monthly expenses? Select all that apply.', 'MULTI', '{"A":"Hostel or PG rent","B":"Weekend outings","C":"Mobile and internet plan","D":"Food delivery"}'::jsonb, 'BUDGETING', ARRAY['STUDENT'], 1, '{"correctSet":["A","C"],"points":10}'::jsonb, 'Select every option that applies.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 90, 'fixed vs. flexible expenses', 'Fixed cost'),
('budgeting_recurring_bills', 'How do you handle recurring bills — rent, EMI, utilities — each month?', 'SINGLE', '{"A":"I sometimes pay late","B":"I pay manually, but on time","C":"Auto-debit is set up for most of them","D":"Auto-debit is set up, and I review it monthly"}'::jsonb, 'BUDGETING', ARRAY['PROFESSIONAL'], 1, '{"optionPoints":{"A":0,"B":5,"C":8,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 100, NULL, 'Direct debit'),
('retiree_budget_fixed_income', 'In retirement, how do you manage monthly expenses against your pension or withdrawal income?', 'SINGLE', '{"A":"I don''t have a clear budget","B":"A rough idea, no formal budget","C":"I track it monthly against my income","D":"I track it monthly and re-check it against inflation each year"}'::jsonb, 'BUDGETING', ARRAY['RETIREE'], 1, '{"optionPoints":{"A":0,"B":3,"C":7,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 110, NULL, 'Personal budget'),
('saving_emergency_fund_months', 'How many months of essential expenses could you cover from money you can withdraw within a few days?', 'NUMBER', NULL, 'SAVING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 2, '{"numberThresholds":[{"min":6,"points":10},{"min":3,"points":6},{"min":1,"points":3},{"min":0,"points":0}]}'::jsonb, 'Count savings accounts, liquid funds and FDs you can break. Leave out stocks, PPF, EPF and gold.', 'months', NULL, NULL, NULL, '{"STUDENT":{"text":"If you suddenly needed money — a broken phone, a doctor''s visit, a trip home — how many months of your usual spending could you cover from your own savings, without asking anyone?","hint":"Count savings you can get to within a few days. Money your family would step in with doesn''t count here."},"RETIREE":{"hint":"Count savings accounts, liquid funds and FDs you can break early. Leave out money locked in SCSS, annuities, equity and gold."}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 120, NULL, 'Emergency fund'),
('saving_emergency_fund_simple', 'Put simply: if your income stopped today, how long could you keep paying rent, food and bills from money you can get to quickly?', 'SINGLE', '{"A":"Less than a month","B":"1 to 3 months","C":"3 to 6 months","D":"More than 6 months"}'::jsonb, 'SAVING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 2, NULL, NULL, NULL, NULL, NULL, NULL, '{"STUDENT":{"text":"Put simply: if your pocket money or stipend stopped, how long could your own savings cover your usual spending — phone, travel, food outside home?"},"RETIREE":{"text":"Put simply: if your pension or other income was held up, how long could you keep paying for food, medicines and bills from money you can get to quickly?"},"PROFESSIONAL":{"text":"Put simply: if you lost your job today, how long could you keep paying rent, EMIs, food and bills from money you can get to quickly?"}}'::jsonb, 'saving_emergency_fund_months', '{"A":{"number":0},"B":{"number":2},"C":{"number":4},"D":{"number":6}}'::jsonb, NULL, NULL, FALSE, 130, NULL, 'Emergency fund'),
('saving_emergency_fund_where', 'Where is the most sensible place to keep an emergency fund?', 'SINGLE', '{"A":"In stocks, so it grows faster","B":"A savings account or liquid fund you can withdraw from any day","C":"Gold jewellery at home","D":"A 5-year locked tax-saver FD"}'::jsonb, 'SAVING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"unknownOrNumberBelow":{"question":"saving_emergency_fund_months","value":3}}'::jsonb, 'Follow-up — your emergency cushion looks thin, so a quick check on where one should live.', FALSE, 140, 'where to keep an emergency fund', 'Money market fund'),
('saving_fd_vs_savings', 'Which of these typically earns a higher rate of interest?', 'SINGLE', '{"A":"A regular savings account","B":"A fixed deposit (FD) at the same bank","C":"They always pay the same rate","D":"A savings account, because you can withdraw any time"}'::jsonb, 'SAVING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 150, 'FD vs. savings account rates', 'Fixed deposit'),
('saving_emergency_fund_purpose', 'What''s the main purpose of an emergency fund?', 'SINGLE', '{"A":"Grow wealth quickly","B":"Cover unexpected essential expenses without new debt","C":"Pay for vacations","D":"Maximise investment returns"}'::jsonb, 'SAVING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 160, 'what an emergency fund is for', 'Emergency fund'),
('retiree_scam_digital_arrest', 'A video caller in uniform says your Aadhaar is linked to a crime, you''re under "digital arrest", and you must transfer money to clear your name. What should you do?', 'SINGLE', '{"A":"Pay quickly and quietly to avoid trouble","B":"Hang up: no police or agency arrests anyone over a video call or asks for money — report it on 1930 or cybercrime.gov.in","C":"Share your bank OTP so they can verify your account","D":"Stay on the call and ask a family member to send the money"}'::jsonb, 'SAVING', ARRAY['RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 170, 'spotting "digital arrest" scams', 'Digital arrest scam'),
('saving_upi_safety', 'A stranger says they sent you money by mistake and sends a UPI request asking you to return it. What should you do?', 'SINGLE', '{"A":"Approve it and enter your UPI PIN — it''s only fair","B":"Don''t approve it: you never need your PIN to receive money — check your bank app and report the request","C":"Share the OTP they ask for so the bank can reverse it","D":"Approve half the amount to be safe"}'::jsonb, 'SAVING', ARRAY['STUDENT'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 180, 'staying safe on UPI', 'Unified Payments Interface'),
('saving_automatic_transfer', 'How do you usually save each month?', 'SINGLE', '{"A":"Whatever is left over, if anything","B":"Occasionally, when I remember","C":"A recurring deposit or SIP is set up","D":"Saving is automated the day I get paid"}'::jsonb, 'SAVING', ARRAY['STUDENT','PROFESSIONAL'], 1, '{"optionPoints":{"A":0,"B":3,"C":7,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, '{"STUDENT":{"options":{"A":"Whatever is left over, if anything","B":"Occasionally, when I remember","C":"A recurring deposit or SIP is set up","D":"I set some aside the day my allowance or stipend arrives"}}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 190, NULL, 'Systematic investment plan'),
('saving_health_insurance', 'What health insurance covers you today?', 'SINGLE', '{"A":"None","B":"Only a policy through my employer or college","C":"A personal or family floater policy","D":"A personal or family policy, plus a top-up or super top-up"}'::jsonb, 'SAVING', ARRAY['STUDENT','PROFESSIONAL'], 1, '{"optionPoints":{"A":0,"B":5,"C":8,"D":10}}'::jsonb, 'A parent''s family floater that includes you counts as a family policy.', NULL, NULL, NULL, NULL, '{"PROFESSIONAL":{"hint":"Your employer''s group cover usually ends the day you leave the job — a policy of your own stays with you.","options":{"A":"None","B":"Only my employer''s group policy","C":"A personal or family floater policy","D":"A personal or family policy, plus a top-up or super top-up"}}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 200, NULL, 'Health insurance in India'),
('dependents', 'How many people depend on your income — a partner, children or parents?', 'SINGLE', '{"A":"No one","B":"1 or 2 people","C":"3 or more people"}'::jsonb, 'SAVING', ARRAY['PROFESSIONAL'], 1, NULL, 'Not scored — it shapes how much risk your plan can take and whether you need life cover.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 210, NULL, NULL),
('saving_term_insurance', 'If something happened to you, what life cover would your family get?', 'SINGLE', '{"A":"None, or only my employer''s group cover","B":"An endowment or money-back policy","C":"A term plan of under 10× my annual income","D":"A term plan of 10× my annual income or more"}'::jsonb, 'SAVING', ARRAY['PROFESSIONAL'], 1, '{"optionPoints":{"A":0,"B":3,"C":6,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"selectedIn":{"question":"dependents","values":["B","C"]}}'::jsonb, 'Follow-up — because others depend on your income.', FALSE, 220, NULL, 'Term life insurance'),
('debt_high_interest_status', 'Do you carry any high-interest debt — an unpaid credit card balance, or a personal or app-based loan above roughly 12% a year?', 'SINGLE', '{"A":"Yes","B":"No — I pay my card in full each month, or have no such loans"}'::jsonb, 'DEBT', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 2, '{"optionPoints":{"A":0,"B":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, '{"STUDENT":{"text":"Do you owe money on a credit card, Buy Now Pay Later (BNPL) or an instant-loan app that you haven''t fully paid off?","options":{"A":"Yes","B":"No — or I don''t use any of these"}}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 230, NULL, 'Credit card interest'),
('debt_high_interest_simple', 'In the last few months, have you paid only part of a credit card bill, or taken a personal or app-based loan?', 'SINGLE', '{"A":"Yes","B":"No — or I don''t have a credit card or loans"}'::jsonb, 'DEBT', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 2, NULL, NULL, NULL, NULL, NULL, NULL, '{"STUDENT":{"text":"In the last few months, have you missed or only part-paid a credit card, Buy Now Pay Later or loan-app payment?"}}'::jsonb, 'debt_high_interest_status', '{"A":{"selected":"A"},"B":{"selected":"B"}}'::jsonb, NULL, NULL, FALSE, 240, NULL, 'Credit card interest'),
('debt_payoff_plan', 'What''s your plan for paying off that high-interest debt?', 'SINGLE', '{"A":"No plan yet","B":"Paying only the minimum due","C":"Paying more than the minimum when I can","D":"A fixed extra amount every month, highest-rate or smallest debt first"}'::jsonb, 'DEBT', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"optionPoints":{"A":0,"B":2,"C":7,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"selectedIn":{"question":"debt_high_interest_status","values":["A"]}}'::jsonb, 'Follow-up — because you''re carrying high-interest debt.', FALSE, 250, NULL, 'Debt snowball method'),
('debt_good_vs_bad', 'Which of these are usually considered “good debt” — the kind that can build long-term value? Select all that apply.', 'MULTI', '{"A":"An education loan for a recognised course","B":"Buy Now Pay Later for the latest phone","C":"A home loan, later in life","D":"An instant-loan app for a weekend trip"}'::jsonb, 'DEBT', ARRAY['STUDENT'], 1, '{"correctSet":["A","C"],"points":10}'::jsonb, 'Select every option that applies.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 260, 'good vs. bad debt', 'Debt'),
('debt_interest_type', 'A credit card typically charges roughly how much interest a year if you carry a balance?', 'SINGLE', '{"A":"3–5%","B":"8–12%","C":"36–45%","D":"80–100%"}'::jsonb, 'DEBT', ARRAY['STUDENT'], 1, '{"correct":"C","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 270, 'what credit cards really charge', 'Credit card interest'),
('debt_student_loan_interest', 'On a regular education loan with no interest subsidy, what happens to interest while you''re studying and in the moratorium?', 'SINGLE', '{"A":"None is charged until repayments start","B":"It keeps building up and gets added to what you owe, unless you pay it","C":"The bank waives it if you finish the course","D":"It''s paid for you by the government"}'::jsonb, 'DEBT', ARRAY['STUDENT'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 280, 'how education-loan interest builds up while you study', 'Student loan'),
('debt_credit_card_habit', 'You''re offered your first credit card. What''s the safest way to use it?', 'SINGLE', '{"A":"Pay the full bill every month, on time","B":"Pay only the minimum due each month","C":"Max it out for the reward points","D":"Never activate it — just keep it in a drawer"}'::jsonb, 'DEBT', ARRAY['STUDENT'], 1, '{"optionPoints":{"A":10,"B":2,"C":0,"D":6}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 290, NULL, 'Credit card'),
('debt_emi_share', 'Roughly how much of your take-home income goes to EMIs and loan repayments each month?', 'SINGLE', '{"A":"None — I have no EMIs","B":"Under 20%","C":"20% to 40%","D":"More than 40%"}'::jsonb, 'DEBT', ARRAY['PROFESSIONAL'], 1, '{"optionPoints":{"A":10,"B":8,"C":4,"D":0}}'::jsonb, 'Banks usually get cautious about lending once this passes 40–50%.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 300, NULL, 'Debt-to-income ratio'),
('debt_loan_priority', 'You''re carrying both a home loan at roughly 8.5% and a credit card balance at roughly 36%. Which should you prioritise paying off faster?', 'SINGLE', '{"A":"The home loan — it''s the bigger number","B":"The credit card — it''s the higher rate","C":"Split extra payments evenly between both","D":"Neither — just pay the minimums on both"}'::jsonb, 'DEBT', ARRAY['PROFESSIONAL'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 310, 'which loan to repay first', 'Debt snowball method'),
('retiree_debt_in_retirement', 'Do you still have any active loans — home, personal, or otherwise — that you''re repaying in retirement?', 'SINGLE', '{"A":"Yes, a large EMI relative to my income","B":"Yes, but a small, manageable EMI","C":"No, I''m debt-free"}'::jsonb, 'DEBT', ARRAY['RETIREE'], 1, '{"optionPoints":{"A":0,"B":5,"C":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 320, NULL, 'Equated monthly installment'),
('risk_market_drop_reaction', 'If your investment portfolio dropped 20% in a month, how would you react?', 'SCALE', NULL, 'RISK', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 2, '{"scale":{"1":0,"2":3,"3":6,"4":8,"5":10}}'::jsonb, NULL, NULL, NULL, NULL, '["Panic and sell everything","Stay invested, maybe buy more"]'::jsonb, '{"STUDENT":{"text":"Imagine ₹10,000 of your savings was invested, and a month later it''s worth ₹8,000. How would you react?"}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 330, NULL, 'Loss aversion'),
('risk_drop_rupees', 'Imagine you invested ₹1,00,000 and a month later it''s worth ₹80,000. What would you most likely do?', 'SINGLE', '{"A":"Sell everything before it falls further","B":"Sell some of it","C":"Leave it alone and wait","D":"Invest a bit more while prices are low"}'::jsonb, 'RISK', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 2, NULL, NULL, NULL, NULL, NULL, NULL, '{"STUDENT":{"text":"Imagine you invested ₹10,000 and a month later it''s worth ₹8,000. What would you most likely do?"}}'::jsonb, 'risk_market_drop_reaction', '{"A":{"scale":1},"B":{"scale":2},"C":{"scale":4},"D":{"scale":5}}'::jsonb, NULL, NULL, FALSE, 340, NULL, 'Loss aversion'),
('risk_equity_experience', 'Have you ever held stocks or equity mutual funds through a big market fall?', 'SINGLE', '{"A":"I''ve never invested in equity","B":"I''ve invested, but never through a big fall","C":"Yes — and I sold during the fall","D":"Yes — and I stayed invested"}'::jsonb, 'RISK', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"optionPoints":{"A":2,"B":5,"C":3,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"unknownOrScaleAtMost":{"question":"risk_market_drop_reaction","value":2}}'::jsonb, 'Follow-up — to understand where your caution about market falls comes from.', FALSE, 350, NULL, 'Stock market crash'),
('risk_volatility_understanding', 'Which of these typically has the highest short-term price volatility?', 'SINGLE', '{"A":"Fixed deposit","B":"PPF (Public Provident Fund)","C":"Equity mutual fund","D":"Savings account"}'::jsonb, 'RISK', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"correct":"C","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 360, 'which investments swing the most', 'Volatility (finance)'),
('risk_horizon', 'When will you need most of the money you''re saving or investing?', 'SINGLE', '{"A":"Within a year","B":"In 1 to 3 years","C":"In 3 to 7 years","D":"Not for 7 years or more"}'::jsonb, 'RISK', ARRAY['STUDENT','PROFESSIONAL'], 2, '{"optionPoints":{"A":2,"B":4,"C":7,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, '{"STUDENT":{"hint":"Think of your bigger plans — a laptop, a course, higher studies, moving city for a first job."}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 370, NULL, 'Time horizon'),
('retiree_inflation_awareness', 'Over a 20-year retirement, which of these typically poses the bigger risk to your purchasing power?', 'SINGLE', '{"A":"Day-to-day market volatility","B":"Inflation quietly eroding fixed income","C":"Bank service charges","D":"Currency exchange rates"}'::jsonb, 'RISK', ARRAY['RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 380, 'inflation risk in retirement', 'Inflation'),
('compounding_rule_of_72', 'Using the Rule of 72, roughly how many years does it take to double your money at 8% annual return?', 'SINGLE', '{"A":"4 years","B":"9 years","C":"14 years","D":"20 years"}'::jsonb, 'COMPOUNDING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 2, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 390, 'the Rule of 72', 'Rule of 72'),
('compounding_early_start', 'Two people invest the same amount monthly. Person A starts at 25, Person B at 35; both stop at 45 and let it grow, untouched, at the same return. Who generally ends up with more?', 'SINGLE', '{"A":"Person A","B":"Person B","C":"They always end up equal","D":"Impossible to know"}'::jsonb, 'COMPOUNDING', ARRAY['STUDENT','PROFESSIONAL'], 2, '{"correct":"A","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 400, 'the cost of starting late', 'Compound interest'),
('compounding_pay_rise', 'You get a 15% raise. What usually does the most for your long-term wealth?', 'SINGLE', '{"A":"Upgrade your lifestyle by the full amount — you''ve earned it","B":"Raise your SIP by part of the raise before your spending catches up","C":"Leave the extra sitting in your savings account","D":"Take a bigger loan now that you can afford a larger EMI"}'::jsonb, 'COMPOUNDING', ARRAY['PROFESSIONAL'], 1, '{"optionPoints":{"A":0,"B":10,"C":4,"D":0}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 410, NULL, 'Lifestyle creep'),
('compounding_basics_probe', 'You deposit ₹10,000 at 10% interest a year, compounded yearly, and don''t touch it. Roughly how much is there after 2 years?', 'SINGLE', '{"A":"₹11,000","B":"₹12,000","C":"₹12,100","D":"₹20,000"}'::jsonb, 'COMPOUNDING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"correct":"C","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"knowledgeGap":"COMPOUNDING"}'::jsonb, 'Follow-up — checking the basics of compounding before we call it a gap.', FALSE, 420, 'how compound interest adds up', 'Compound interest'),
('investing_index_fund_def', 'What does an index fund do?', 'SINGLE', '{"A":"Actively picks stocks to try to beat the market","B":"Tracks a market index, like the Nifty 50, passively","C":"Guarantees a fixed return","D":"Only invests in gold"}'::jsonb, 'INVESTING', ARRAY['STUDENT','PROFESSIONAL'], 2, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 430, 'what index funds do', 'Index fund'),
('investing_first_step', 'As a student with limited money to invest, what''s a reasonable way to start?', 'SINGLE', '{"A":"Wait until I have a large lump sum","B":"Try to time the market for the perfect entry point","C":"Start a small SIP in an index fund","D":"Put everything into one hot stock tip"}'::jsonb, 'INVESTING', ARRAY['STUDENT'], 1, '{"optionPoints":{"A":2,"B":0,"C":10,"D":0}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 440, NULL, 'Dollar-cost averaging'),
('investing_scam_check', 'A senior adds you to a Telegram group promising "guaranteed 10% a month" from trading or crypto. What''s the best way to read it?', 'SINGLE', '{"A":"Join fast — early members earn the most","B":"Try a small amount first to test it","C":"Treat it as a likely scam: no genuine investment can guarantee returns like that","D":"It''s fine if lots of people vouch for it"}'::jsonb, 'INVESTING', ARRAY['STUDENT'], 1, '{"correct":"C","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 450, 'spotting "guaranteed return" scams', 'Ponzi scheme'),
('investing_elss_lockin', 'What is the lock-in period for ELSS (tax-saving) mutual funds in India?', 'SINGLE', '{"A":"No lock-in","B":"1 year","C":"3 years","D":"5 years"}'::jsonb, 'INVESTING', ARRAY['PROFESSIONAL'], 1, '{"correct":"C","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 460, 'the ELSS lock-in', 'Equity Linked Savings Scheme'),
('investing_80c_options', 'Under the old tax regime, which of these can you claim as deductions under Section 80C? Select all that apply.', 'MULTI', '{"A":"PPF","B":"ELSS mutual funds","C":"Regular savings account","D":"5-year tax-saver FD"}'::jsonb, 'INVESTING', ARRAY['PROFESSIONAL'], 1, '{"correctSet":["A","B","D"],"points":10}'::jsonb, 'Select every option that applies. The new regime (the default since 2023) doesn''t allow 80C.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 470, 'Section 80C options', 'Income tax in India'),
('investing_tax_regime', 'Since FY 2025-26, under the new tax regime, a salaried person earning up to about how much a year pays no income tax at all?', 'SINGLE', '{"A":"₹5 lakh","B":"₹7.75 lakh","C":"₹12.75 lakh","D":"₹20 lakh"}'::jsonb, 'INVESTING', ARRAY['PROFESSIONAL'], 1, '{"correct":"C","points":10}'::jsonb, 'The new regime is the default; you can still choose the old one if your deductions (80C, HRA, home loan) are large.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 480, 'the new tax regime''s ₹12.75 lakh zero-tax limit', 'Income tax in India'),
('retiree_scss_awareness', 'What is the Senior Citizens'' Savings Scheme (SCSS)?', 'SINGLE', '{"A":"A government-backed fixed-income scheme, mainly for people aged 60 and over","B":"A private equity mutual fund","C":"A type of health insurance policy","D":"A tax filing category"}'::jsonb, 'INVESTING', ARRAY['RETIREE'], 1, '{"correct":"A","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 490, 'the Senior Citizens'' Savings Scheme', 'India Post'),
('retiree_swp_def', 'What does an SWP (Systematic Withdrawal Plan) let you do?', 'SINGLE', '{"A":"Invest a fixed amount every month","B":"Withdraw a fixed amount from your investments at regular intervals","C":"Automatically switch between mutual funds","D":"Borrow against your mutual fund units"}'::jsonb, 'INVESTING', ARRAY['RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 500, 'systematic withdrawal plans (SWP)', 'Retirement spend-down'),
('investing_basics_probe', 'Why is spreading your money across many companies usually safer than putting it all into one?', 'SINGLE', '{"A":"It guarantees a higher return","B":"One company doing badly hurts you much less","C":"It avoids all taxes","D":"It isn''t — one good company is always safer"}'::jsonb, 'INVESTING', ARRAY['STUDENT','PROFESSIONAL','RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"knowledgeGap":"INVESTING"}'::jsonb, 'Follow-up — checking the basics of investing before we call it a gap.', FALSE, 510, 'diversification', 'Diversification (finance)'),
('retirement_ppf_lockin', 'What is the standard maturity period of a PPF account in India?', 'SINGLE', '{"A":"5 years","B":"10 years","C":"15 years","D":"21 years"}'::jsonb, 'RETIREMENT', ARRAY['PROFESSIONAL','RETIREE'], 1, '{"correct":"C","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 520, 'PPF maturity', 'Public Provident Fund (India)'),
('retirement_readiness', 'How confident are you that your current savings and investments are on track for retirement?', 'SCALE', NULL, 'RETIREMENT', ARRAY['PROFESSIONAL','RETIREE'], 1, '{"scale":{"1":0,"2":3,"3":5,"4":8,"5":10}}'::jsonb, NULL, NULL, NULL, NULL, '["Not confident","Very confident"]'::jsonb, '{"RETIREE":{"text":"How confident are you that your savings and investments will last through your retirement?"}}'::jsonb, NULL, NULL, NULL, NULL, FALSE, 530, NULL, 'Retirement planning'),
('retirement_nps_tax', 'Under the old tax regime, which section gives an extra deduction of up to ₹50,000 for your own NPS contributions, beyond the ₹1.5 lakh 80C limit?', 'SINGLE', '{"A":"80D","B":"80CCD(1B)","C":"80G","D":"80TTA"}'::jsonb, 'RETIREMENT', ARRAY['PROFESSIONAL'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 540, 'the extra NPS deduction, 80CCD(1B)', 'National Pension System'),
('retirement_epf_job_change', 'When you change jobs, what''s usually best to do with your EPF balance?', 'SINGLE', '{"A":"Withdraw it — it''s a nice bonus","B":"Transfer it to your new employer''s account using your UAN","C":"Leave it in the old account and forget about it","D":"Withdraw half, keep half"}'::jsonb, 'RETIREMENT', ARRAY['PROFESSIONAL'], 1, '{"optionPoints":{"A":0,"B":10,"C":4,"D":2}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 550, NULL, 'Employees'' Provident Fund Organisation'),
('retirement_corpus_estimate', 'Roughly how many times your current annual expenses do you think you''ll need saved by retirement?', 'NUMBER', NULL, 'RETIREMENT', ARRAY['PROFESSIONAL'], 1, '{"numberThresholds":[{"min":20,"points":10},{"min":15,"points":6},{"min":10,"points":3},{"min":0,"points":0}]}'::jsonb, NULL, '× annual expenses', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 560, NULL, 'Trinity study'),
('retiree_runway_years', 'At your current rate of spending from savings, roughly how many years do you estimate your retirement corpus would comfortably last?', 'NUMBER', NULL, 'RETIREMENT', ARRAY['RETIREE'], 1, '{"numberThresholds":[{"min":25,"points":10},{"min":15,"points":6},{"min":8,"points":3},{"min":0,"points":0}]}'::jsonb, NULL, 'years', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 570, NULL, 'Retirement spend-down'),
('retiree_healthcare_fund', 'Do you have a dedicated health insurance or medical emergency fund, separate from your main retirement corpus?', 'SINGLE', '{"A":"No","B":"I''ve been meaning to","C":"Yes, a small one","D":"Yes, sized for a major medical event"}'::jsonb, 'RETIREMENT', ARRAY['RETIREE'], 1, '{"optionPoints":{"A":0,"B":3,"C":7,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 580, NULL, 'Health insurance in India'),
('retiree_withdrawal_rate', 'Roughly what share of your savings can you withdraw each year, so they''re likely to last 25–30 years?', 'SINGLE', '{"A":"About 1%","B":"About 3–4%","C":"About 8–10%","D":"About 15%"}'::jsonb, 'RETIREMENT', ARRAY['RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 590, 'a safe yearly withdrawal rate', 'Trinity study'),
('retiree_nomination_will', 'Have you added nominees to your bank accounts, FDs and investments, and made a will?', 'SINGLE', '{"A":"Neither","B":"Nominees on some accounts, no will","C":"Nominees on all accounts, but no will yet","D":"Nominees everywhere, and a will"}'::jsonb, 'RETIREMENT', ARRAY['RETIREE'], 1, '{"optionPoints":{"A":0,"B":3,"C":6,"D":10}}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, 600, NULL, 'Will and testament'),
('retiree_form_15h', 'If your total income is below the taxable limit, which form stops your bank deducting tax (TDS) from your FD interest?', 'SINGLE', '{"A":"Form 15G","B":"Form 15H","C":"Form 16","D":"Form 26AS"}'::jsonb, 'RETIREMENT', ARRAY['RETIREE'], 1, '{"correct":"B","points":10}'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 610, 'Form 15H for tax on FD interest', 'Tax deduction at source')
ON CONFLICT (code) DO UPDATE SET
    text = EXCLUDED.text, type = EXCLUDED.type, options = EXCLUDED.options,
    category = EXCLUDED.category, applicable_profiles = EXCLUDED.applicable_profiles,
    weight = EXCLUDED.weight, rubric = EXCLUDED.rubric, hint = EXCLUDED.hint,
    unit = EXCLUDED.unit, min_value = EXCLUDED.min_value, max_value = EXCLUDED.max_value,
    scale_labels = EXCLUDED.scale_labels, variants = EXCLUDED.variants,
    clarifies = EXCLUDED.clarifies, value_map = EXCLUDED.value_map, ask_if = EXCLUDED.ask_if,
    follow_up_reason = EXCLUDED.follow_up_reason, advanced = EXCLUDED.advanced,
    sort_order = EXCLUDED.sort_order, knowledge_topic = EXCLUDED.knowledge_topic,
    wiki_title = EXCLUDED.wiki_title, active = TRUE;

CREATE INDEX idx_questions_active_sort ON questions (active, sort_order);
