-- Regenerate, draft history, the itemised risk capacity, a user-chosen risk
-- band, feedback on AI-written text, and the profile each session was taken as.

-- ---------------------------------------------------------------------------
-- sessions.profile_type: the profile the assessment was taken as. A user can
-- change profile later; their earlier results must still be scored, planned
-- and labelled as the profile they answered for. Backfilled from the user.
-- ---------------------------------------------------------------------------
ALTER TABLE sessions ADD COLUMN profile_type VARCHAR(16);
UPDATE sessions s SET profile_type = u.profile_type FROM users u WHERE u.id = s.user_id;
ALTER TABLE sessions
    ALTER COLUMN profile_type SET NOT NULL,
    ADD CONSTRAINT sessions_profile_type_chk
        CHECK (profile_type IN ('STUDENT', 'PROFESSIONAL', 'RETIREE'));

-- ---------------------------------------------------------------------------
-- literacy_scores: every narrative draft, oldest first. Each element is a
-- NarrativeDraft: {"content": {...}, "provider": "...", "model": "...",
--  "latencyMs": n, "tokens": n, "createdAt": "...", "pointIds": [...],
--  "angle": "..."}. provider "template" means no model answered.
-- narrative_json stays the latest draft, so existing readers keep working.
-- ---------------------------------------------------------------------------
ALTER TABLE literacy_scores
    ADD COLUMN narrative_drafts JSONB NOT NULL DEFAULT '[]'::jsonb;

-- ---------------------------------------------------------------------------
-- risk_profiles
--   capacity_factors  the signed factors that sum to capacity_score, so the
--                     screen can show exactly how the number was reached
--   selected_band     the band the user chose to plan around instead of the
--                     calculated one; NULL means "use risk_band"
--   narrative_drafts  drafts per band: {"BALANCED": [draft, ...], ...}, since
--                     the rationale describes whichever band is active
-- ---------------------------------------------------------------------------
ALTER TABLE risk_profiles
    ADD COLUMN capacity_factors JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN selected_band    VARCHAR(16),
    ADD COLUMN model_used       VARCHAR(128),
    ADD COLUMN narrative_drafts JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD CONSTRAINT risk_profiles_selected_band_chk
        CHECK (selected_band IS NULL OR selected_band IN
               ('CONSERVATIVE', 'MODERATE', 'BALANCED', 'GROWTH', 'AGGRESSIVE'));

-- ---------------------------------------------------------------------------
-- narrative_feedback: thumbs up / down on one draft of an AI-written card.
-- One row per (session, target, band, draft); a second click replaces it.
-- ---------------------------------------------------------------------------
CREATE TABLE narrative_feedback (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  UUID        NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
    target      VARCHAR(16) NOT NULL,
    band        VARCHAR(16) NOT NULL DEFAULT '',
    draft_index INT         NOT NULL,
    rating      VARCHAR(8)  NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT narrative_feedback_target_chk CHECK (target IN ('SCORE', 'RISK')),
    CONSTRAINT narrative_feedback_rating_chk CHECK (rating IN ('UP', 'DOWN')),
    CONSTRAINT narrative_feedback_uk UNIQUE (session_id, target, band, draft_index)
);
